// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDsoEYru3mfeqzfVFV-lRdsWI7e60Zzf0',
    appId: '1:577791769210:web:ec092762a9533cc81a99c3',
    messagingSenderId: '577791769210',
    projectId: 'danamu',
    authDomain: 'danamu-1c642.firebaseapp.com',
    storageBucket: 'danamu.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtBWBdhZjUzpIQH8MLUtEP2FdSPmdnaDc',
    appId: '1:577791769210:android:394113dd087d890e1a99c3',
    messagingSenderId: '577791769210',
    projectId: 'danamu',
    storageBucket: 'danamu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc3dErTMRZOBVEeUcnrnslaFAmEzWwyFM',
    appId: '1:577791769210:ios:385cbf4980c1c89c1a99c3',
    messagingSenderId: '577791769210',
    projectId: 'danamu',
    storageBucket: 'danamu.firebasestorage.app',
    iosBundleId: 'com.example.templateProjek',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDc3dErTMRZOBVEeUcnrnslaFAmEzWwyFM',
    appId: '1:577791769210:ios:385cbf4980c1c89c1a99c3',
    messagingSenderId: '577791769210',
    projectId: 'danamu',
    storageBucket: 'danamu.firebasestorage.app',
    iosBundleId: 'com.example.templateProjek',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDsoEYru3mfeqzfVFV-lRdsWI7e60Zzf0',
    appId: '1:577791769210:web:4114bd20478a2ecf1a99c3',
    messagingSenderId: '577791769210',
    projectId: 'danamu',
    authDomain: 'danamu-1c642.firebaseapp.com',
    storageBucket: 'danamu.firebasestorage.app',
  );
}
